server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authUser
          uri: lb://AUTHUSER
          predicates:
            - Path=/api/v1/auth/**
        - id: userService
          uri: lb://AUTHUSER
          predicates:
            - Path=/api/v1/user/**

        - id: documentService
          uri: lb://CREDITSERVICE
          predicates:
            - Path=/v1/api/document/**
        - id: creditService
          uri: lb://CREDITSERVICE
          predicates:
            - Path=/api/v1/credit/**
        - id: demande-service
          uri: lb://DEMANDE-SERVICE
          predicates:
            - Path=/api/v1/demande/**
