server:
  port: 8222
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: authUser
          uri: lb://AUTHUSER
          predicates:
            - Path=/api/v1/auth/**
        - id: userService
          uri: lb://AUTHUSER
          predicates:
            - Path=/api/v1/user/**

        - id: documentService
          uri: lb://CREDITSERVICE
          predicates:
            - Path=/v1/api/document/**
        - id: creditService
          uri: lb://CREDITSERVICE
          predicates:
            - Path=/api/v1/credit/**
        - id: demande-service
          uri: lb://DEMANDE-SERVICE
          predicates:
            - Path=/api/v1/demande/**
